Meteor.methods
  'sendFeedback': (body, any_variable) ->
	    # Don't wait for result
	    @unblock()
	    # Define the settings
	    postURL = process.env.MAILGUN_API_URL + '/' + process.env.MAILGUN_DOMAIN + '/messages'
	    options = 
	      auth: 'api:' + process.env.MAILGUN_API_KEY
	      params:
	        'from': 'Movie at My Place &lt;info@movieatmyplace.com>'
	        'to': [ 'krister.viirsaar@gmail.com' ]
	        'subject': 'movieatmyplace.com quick feedback'
	        'html': body

	    onError = (error, result) ->
	      if error
	        console.log 'Error: ' + error
	      return

	    # Send the request
	    Meteor.http.post postURL, options, onError
	    return
	'sendEmail': (mailFields) ->
		console.log 'about to send email...'
		check [			
			mailFields.to
		    mailFields.from
		    mailFields.subject
		    mailFields.text
			  ], [ String ]
		# Let other method calls from the same client start running,
		# without waiting for the email sending to complete.
		@unblock()
		html = getEmailBody(mailFields)

		Meteor.Mailgun.send
			to: mailFields.to
			from: mailFields.from
			subject: mailFields.subject
			text: mailFields.text
			html: html
		,(result)->
			return result
		console.log 'email sent!'

		return
# ---
# generated by js2coffee 2.1.0